name: Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: extractions/setup-just@v4
      - uses: actions/setup-go@v7
        with:
          go-version: "1.27"
      - uses: golangci/golangci-lint-action@v9
        with:
          version: v2.13.2
          install-only: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - run: just lint
